application: <project-id>
version: phpmyadmin
runtime: php
api_version: 1

handlers:
- url: /phpMyAdmin/(.*\.(ico$|jpg$|png$|gif$))
  static_files: phpMyAdmin/\1
  upload: phpMyAdmin/(.*\.(ico$|jpg$|png$|gif$))
  application_readable: true

- url: /phpMyAdmin/(.*\.(htm$|html$|css$|js$))
  static_files: phpMyAdmin/\1
  upload: phpMyAdmin/(.*\.(htm$|html$|css$|js$))
  application_readable: true

- url: /(.*\.(ico$|jpg$|png$|gif$))
  static_files: phpMyAdmin/\1
  upload: phpMyAdmin/(.*\.(ico$|jpg$|png$|gif$))
  application_readable: true

- url: /(.*\.(htm$|html$|css$|js$))
  static_files: phpMyAdmin/\1
  upload: phpMyAdmin/(.*\.(htm$|html$|css$|js$))
  application_readable: true

- url: /phpMyAdmin/(.*\.(php$))
  script: phpMyAdmin/\1
  login: admin

- url: /(.*\.(php$))
  script: phpMyAdmin/\1
  login: admin

- url: /(.+)
  script: phpMyAdmin/index.php
  login: admin

- url: /.*
  script: phpMyAdmin/index.php
  login: admin
